#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint

# Get the current branch name
branch=$(git rev-parse --abbrev-ref HEAD)

# Define the allowed branch naming patterns
valid_branch_regex="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)\/[a-z0-9-]+$"
valid_special_branches_regex="^(develop|master|main)$"

if ! echo "$branch" | grep -Eq "$valid_branch_regex" && ! echo "$branch" | grep -Eq "$valid_special_branches_regex"; then
  echo "⧗ input: $branch"
  echo "✖ branch name must follow the pattern: <type>/<branch-name>, integration-qa/<version>, integration/<version>, release/<version>, or one of: develop, master [branch-pattern-invalid]"
  echo "✖ valid types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
  echo ""
  echo "found 1 problem, 0 warnings"
  echo "ⓘ Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint"
  echo ""
  echo "To rename your branch, run: git branch -m <new-branch-name>"
  echo ""
  exit 1
fi

echo "✅ Branch name '$branch' is valid."
